# Generated by Django 5.0.1 on 2024-01-27 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='travel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
