# Generated by Django 5.0.1 on 2024-01-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_travel_active_travel_created_travel_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
