# Generated by Django 5.0.1 on 2024-01-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_travel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='forecast',
            field=models.TimeField(editable=False),
        ),
    ]
