# Generated by Django 5.0.1 on 2024-01-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_travel_forecast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='destiny',
            new_name='destination',
        ),
    ]
