# Generated by Django 5.0.1 on 2024-01-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_destiny_travel_destination'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travel',
            options={'ordering': ['id'], 'verbose_name': 'Travel', 'verbose_name_plural': 'Travels'},
        ),
    ]
