# Generated by Django 5.0.1 on 2024-01-27 23:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_travel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
