# Generated by Django 5.0.1 on 2024-02-08 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='category',
            new_name='type',
        ),
    ]
