# Generated by Django 5.0.1 on 2024-02-08 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_category_travel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='type',
            new_name='category',
        ),
    ]
