# Generated by Django 5.0.1 on 2024-02-08 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_travel_destination_alter_travel_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='date',
            new_name='arrival_date',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='arrival',
            new_name='arrival_time',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='departure',
            new_name='departure_time',
        ),
        migrations.AddField(
            model_name='travel',
            name='departure_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 8, 1, 46, 32, 630674, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
