# Generated by Django 5.0.1 on 2024-02-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_date_travel_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='forecast',
            field=models.DurationField(),
        ),
    ]
