# Generated by Django 5.0.1 on 2024-02-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_travel_forecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='seats',
            field=models.IntegerField(default=48),
            preserve_default=False,
        ),
    ]
