# Generated by Django 5.0.1 on 2024-02-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_travel_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='seats',
        ),
        migrations.AddField(
            model_name='travel',
            name='bus',
            field=models.UUIDField(null=True),
        ),
    ]
