# Generated by Django 5.0.1 on 2024-02-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_travel_seats_travel_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='bus',
            field=models.UUIDField(),
        ),
    ]
